name: "LibriTTS"
lang_id: "en"

data_dir: "preprocessed_data/LibriTTS"

subsets:
    train: "train-clean-100.txt"
    val: "val-clean.txt"
    test: "test-clean.txt"

text_cleaners: ["english_cleaners"]
