optimizer:
  batch_size: 16
  betas: [0.9, 0.999]
  eps: 0.000000001
  weight_decay: 0.000001
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [30000, 40000, 50000]
  anneal_rate: 0.3
step:
  total_step: 100000
  log_step: 100
  synth_step: 2500
  val_step: 10000
  save_step: 10000
